# Generated by Django 4.2.6 on 2023-12-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion', models.CharField(max_length=255, verbose_name='Numero de la habitacion')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de la habitacion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la habitacion')),
                ('terraza', models.BooleanField(verbose_name='¿Hay terraza?')),
                ('cocina', models.BooleanField(verbose_name='¿Hay cocina?')),
                ('disponibilidad', models.BooleanField(verbose_name='¿Esta disponible?')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreHotel', models.CharField(max_length=255, verbose_name='Nombre del hotel')),
                ('direccionHotel', models.CharField(max_length=255, verbose_name='Direccion del hotel')),
                ('numberHotel', models.IntegerField(verbose_name='Numero de la direccion del hotel')),
                ('habitacionHotel', models.IntegerField(verbose_name='Numero de habitaciones')),
                ('tarifaHotel', models.FloatField(verbose_name='Tarifa del hotel')),
                ('phoneHotel', models.CharField(max_length=15, verbose_name='Numero de telefono del hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rutClient', models.CharField(max_length=15, verbose_name='Rut')),
                ('nombreClient', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidoClient', models.CharField(max_length=255, verbose_name='Apellido')),
                ('fonoClient', models.CharField(max_length=15, verbose_name='Numero telefonico')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PasajeroHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('llegadaClient', models.DateTimeField(verbose_name='Día de llega')),
                ('salidaClient', models.DateTimeField(verbose_name='Dia de salida')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.habitacion', verbose_name='Numero de habitacion')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel', verbose_name='Direccion')),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.pasajero', verbose_name='Nombre del Pasajero')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='idHotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel', verbose_name='Dirección del Hotel'),
        ),
    ]
