# Generated by Django 4.2.6 on 2023-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fechaNacimiento',
            field=models.DateField(blank=True, help_text='Ej: 1999-10-28', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phoneHotel',
            field=models.CharField(help_text='Ej: +569787878', max_length=15, verbose_name='Numero de telefono del hotel'),
        ),
        migrations.AlterField(
            model_name='pasajerohabitacion',
            name='llegadaClient',
            field=models.DateTimeField(help_text='Ej: 2023-11-29 20:30', verbose_name='Día de llega'),
        ),
        migrations.AlterField(
            model_name='pasajerohabitacion',
            name='salidaClient',
            field=models.DateTimeField(help_text='Ej: 2023-11-30 20:30', verbose_name='Dia de salida'),
        ),
    ]
