# Generated by Django 4.2.6 on 2023-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_remove_pasajero_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='direccionHotel',
            field=models.CharField(help_text='Ej: Lalo Lala', max_length=255, verbose_name='Direccion del hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='numberHotel',
            field=models.IntegerField(help_text='Ej: 1111', verbose_name='Numero de la direccion del hotel'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='apellidoClient',
            field=models.CharField(help_text='Brock', max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='email',
            field=models.EmailField(help_text='ads@acb.cl', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='fonoClient',
            field=models.CharField(help_text='Ej: +569787878', max_length=15, verbose_name='Numero telefonico'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='nombreClient',
            field=models.CharField(help_text='Eddy', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='rutClient',
            field=models.CharField(help_text='Ej: 11.111.111-1', max_length=15, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='pasajerohabitacion',
            name='llegadaClient',
            field=models.DateTimeField(verbose_name='Día de llega'),
        ),
        migrations.AlterField(
            model_name='pasajerohabitacion',
            name='salidaClient',
            field=models.DateTimeField(verbose_name='Dia de salida'),
        ),
    ]
